# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
    minecraft_version=26.1.2
    loader_version=0.19.2
    loom_version=1.16-SNAPSHOT

# Mod Properties
	mod_version = 1.6.6
	maven_group = me.katanya04
	archives_base_name = mine-spawners

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.149.1+26.1.2
	modmenu_version=18.0.0-beta.1

